# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
platform :ios, '9.0'

target 'TheWeedTube' do
 pod 'AWSS3'
 pod 'AWSSES'
 pod 'IQKeyboardManagerSwift'
 pod 'SVProgressHUD'
 pod 'Alamofire', '~> 4.4’
 pod 'ReachabilitySwift'
 pod 'ActionSheetPicker-3.0'
 pod 'SDWebImage'
 pod 'Hue'
 pod 'SideMenu', '~> 4.0.0'
 pod 'UIScrollView-InfiniteScroll'
 pod 'NotificationBannerSwift'
 pod 'Fabric'
 pod 'Crashlytics'
 pod 'Firebase/Core'
 pod 'Firebase/Messaging'
 pod 'NotificationBannerSwift'
 pod 'mopub-ios-sdk'
 pod 'JWPlayer-SDK', '~> 3.3.0'
end
