platform :ios, ‘9.0’
use_frameworks!

target 'HiteshPractical' do
    pod 'Alamofire', '~> 4.6’
    pod 'SDWebImage', '~> 4.0'
    pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
    pod 'ReachabilitySwift'
end
